### ISSUE TITLE
forum.privacore.com/categories/help not found

### ISSUE THREAD

**Issue by grahamperrin** [privacore/helppages-findx#43]
At the foot of https://help.findx.com/en/beta (maybe also at the foot of other pages): 

> **NEED MORE HELP? ASK THE COMMUNITY**

– with reference to <https://forum.privacore.com/categories/help/>, which is not found. 

Maybe better to refer to https://forum.privacore.com/

**Comment by brianschildt** [comment]
Thanks for the feedback - fixed it.
